### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by richd67** [hankhank10/loglink-server#40]
Stopped working this morning now asking for a beta code

**Comment by hankhank10** [comment]
Yes sorry about that, had a database issue so needed to do a reset. Let me know your email and I’ll send you another invite.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by richd67** [comment]
richard@davison.scot

Cheers

**Comment by hankhank10** [comment]
Should be with you now @richd67 - let me know if it's working

**Comment by richd67** [comment]
Cheers all working again
